blank_issues_enabled: false
contact_links:
  - name: PlusCore Discord Server
    url: https://discord.gg/PlusCore
    about: Ask questions, receive support, and discuss with the community in our Discord server.
